
DROP TABLE MEMBERS;
CREATE TABLE MEMBERS(
-- 아이디
	MEMBER_ID VARCHAR2(100) NOT NULL PRIMARY KEY,
-- 비밀번호
	MEMBER_PW CHAR(40) NOT NULL,
    
	MEMBER_NAME VARCHAR2(20) NOT NULL,
-- 휴대폰번호
	MEMBER_PHONE VARCHAR2(20),
-- 이메일
	MEMBER_EMAIL VARCHAR2(300),
-- 생년월일
	MEMBER_BIRTH DATE,
-- 성별
	GENDER CHAR(6),
	
	SESSION_KEY VARCHAR2(50) NOT NULL DEFAULT 'none',

	SESSION_LIMIT TIMESTAMP,
);